### ISSUE TITLE
run dx experiment

### ISSUE THREAD

**Issue by bennet21** [CLPHUU/IceAndClimate#4]
- create dx and ntpy arrays (last one inferred from dx) (go up with dx, dont go too small)
- create plots:
1. response time as function of ELA for different dx
2. mass as function of ELA for different dx

**Comment by AstroVasseL** [comment]
ELA 1600 initial
change dx 50 to 500, steps 50
dt

**Comment by AstroVasseL** [comment]
response time vs dEla, dx different colours for different dx
